/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TheSumOfSameElementsAndCompareWithANumber;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        
    }

    public static Integer sumOfSameElements(ArrayList<Integer> array, ArrayList<Integer> arrayTwo,ArrayList<Integer> arrayThree) {
        
        int count = 0;
        if(array == null || arrayTwo == null || arrayThree == null)
            return 0;
        for(int i=0 ; i < array.size() ; i++){
            if(arrayTwo.contains(array.get(i)) && arrayThree.contains(array.get(i))){
                count+=array.get(i);
                arrayTwo.remove(array.get(i));
                arrayThree.remove(array.get(i));
            }
        }

        return count;
    }

    public static boolean compare(int count , int number) {
        
        if(count < number)
            return true;
        else
            return false;
    }
}
